### ISSUE TITLE
Running on Linux?

### ISSUE THREAD

**Issue by cachuzo** [Vetalb60/WhatsDumpExtractor#1]
Hello @Vetalb60 !!

I follow to suggestion to try this project (https://github.com/MarcoG3/WhatsDump/issues/67#issuecomment-877693561).

I'm a Linux user... as I can see... there is no distribution of HAXM. Is it really mandatory to run the extractor?

Thanks!!!

**Comment by Vetalb60** [comment]
I mean if you have any questions or problems you can use it. i got the same errors but i run whatsdump successfully on windows.

 I have not tried running whatsdump and WDE on linux. Without HAXM you won't run android emulator on windows. 

In any case, you can run whatsdump through the virtual machine.
